version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile.prod
      args:
        - VERSION=1.23
        - NGINX_CONF_FILE
        - NGINX_STATIC_FILES_FOLDER
        - CODE_FOLDER
    ports:
      - ${NGINX_PORT}:80
  php:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile.prod
    environment:
      - APP_NAME=${LARAVEL_APP_NAME}
      - APP_ENV=${LARAVEL_APP_ENV}
      - APP_KEY=${LARAVEL_APP_KEY}
      - APP_DEBUG=${LARAVEL_APP_DEBUG}
      - LOG_CHANNEL=${LARAVEL_LOG_CHANNEL}
      - MARIADB_HOST
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    command: sh -c "composer install && php-fpm"
  maria_db:
    image: mariadb:10.3
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - maria_db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

volumes:
  maria_db_data:
